language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - build-essential
      - libssl-dev
      - libffi-dev
      - python-dev
      - python-pip
      - python-pysnmp4
      - snmp
install:
  - pip install --upgrade pip
  - pip install -r build-requirements.txt
  - pip install -r requirements.txt
script:
  - make all
